name: CiCd-S3-Runner

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Start Build Process"

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Check Code and install Dependencies
        run: |
          ls
          node -v
          npm ci

      - name: Build
        run: |
          npm run build
          ls
